### ISSUE TITLE
Optimize API daily usage

### ISSUE THREAD

**Issue by Mincka** [sepiroth887/accu-mqtt#11]
It could be great to call the API during daytime to double the precision when it's relevant.

Instead of calling the API once per hour, call it every 30 minutes during 12 hours.

To have such flexibility, this program should not rely on internal crontab but instead subscribe to a topic and call the API only when requested.

Edit:
Actually, I'm trying another approach with REST Sensor with large interval and updates triggered by an automation.
In the end, it seems easier to maintain if you use Home Assistant.

```yaml
  - platform: rest
    name: "AccuWeather MinuteCast"
    resource: "https://dataservice.accuweather.com/forecasts/v1/minute?apikey=xxx&q=xxx,xxx&language=en-us&details=true"
    method: GET
    headers:
      Content-Type: application/json
    value_template: "{{ now().isoformat() }}"
    json_attributes:
      - Summary
      - Summaries
    scan_interval: 360000
```

Extraction of the data could be done with template sensors (combination of Summary + Summaries).
Below an example with the extraction of the first period but multiple ones could be present.

```yaml
template:
  - sensor:
      - name: "AccuWeather Start Minute"
        state: >
          {% if state_attr('sensor.accuweather_minutecast', 'Summaries') and 
                 state_attr('sensor.accuweather_minutecast', 'Summaries')|length > 0 %}
            {{ state_attr('sensor.accuweather_minutecast', 'Summaries')[0].StartMinute }}
          {% else %}
            unknown
          {% endif %}

      - name: "AccuWeather End Minute"
        state: >
          {% if state_attr('sensor.accuweather_minutecast', 'Summaries') and 
                 state_attr('sensor.accuweather_minutecast', 'Summaries')|length > 0 %}
            {{ state_attr('sensor.accuweather_minutecast', 'Summaries')[0].EndMinute }}
          {% else %}
            unknown
          {% endif %}

      - name: "AccuWeather Count Minute"
        state: >
          {% if state_attr('sensor.accuweather_minutecast', 'Summaries') and 
                 state_attr('sensor.accuweather_minutecast', 'Summaries')|length > 0 %}
            {{ state_attr('sensor.accuweather_minutecast', 'Summaries')[0].CountMinute }}
          {% else %}
            unknown
          {% endif %}

      - name: "AccuWeather Minute Text"
        state: >
          {% if state_attr('sensor.accuweather_minutecast', 'Summaries') and 
                 state_attr('sensor.accuweather_minutecast', 'Summaries')|length > 0 %}
            {{ state_attr('sensor.accuweather_minutecast', 'Summaries')[0].MinuteText }}
          {% else %}
            unknown
          {% endif %}

      - name: "AccuWeather Type"
        state: >
          {% if state_attr('sensor.accuweather_minutecast', 'Summaries') and 
                 state_attr('sensor.accuweather_minutecast', 'Summaries')|length > 0 %}
            {{ state_attr('sensor.accuweather_minutecast', 'Summaries')[0].Type }}
          {% else %}
            unknown
          {% endif %}

      - name: "AccuWeather Type ID"
        state: >
          {% if state_attr('sensor.accuweather_minutecast', 'Summaries') and 
                 state_attr('sensor.accuweather_minutecast', 'Summaries')|length > 0 %}
            {{ state_attr('sensor.accuweather_minutecast', 'Summaries')[0].TypeId }}
          {% else %}
            unknown
          {% endif %}
```

You can also replicate the logic of shifting the time in the template by using the value of the `AccuWeather MinuteCast` sensor which is the time of the last update.

<img width="527" alt="Image" src="https://github.com/user-attachments/assets/db20464f-33a8-4e00-b3f0-bc3f754056c5" />

Automation:
```
alias: Call AccuWeather MinuteCast API every 30 minutes during daylight
description: ""
triggers:
  - trigger: time_pattern
    minutes: /30
conditions:
  - condition: sun
    after: sunrise
    before: sunset
actions:
  - action: homeassistant.update_entity
    metadata: {}
    data:
      entity_id:
        - sensor.accuweather_minutecast
mode: single
```
